name: Deployment
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deploy production
        run: |
          echo "${{ secrets.KEY }}" > ./key
          chmod 600 ./key
          ssh -tt -o StrictHostKeyChecking=no -i ./key -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} ./gamersnet_deploy.sh
