name: Frontend Testing
on:
  push:
    paths: ['gamersnet_frontend/**']
jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test frontend
        run: |
          cd gamersnet_frontend
          npm ci
          npm test
